name: pixeltime
description: "Create pixel based art for your games or projects."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  uuid: ^4.5.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0
  sqflite_common_ffi_web: ^1.1.0
  args: ^2.7.0
  logger: ^2.6.2
  path_provider: ^2.1.5
  path: ^1.9.1
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Pixelify
      fonts:
        - asset: assets/fonts/PixelifySans-VariableFont_wght.ttf
